### PR TITLE
Feat: removed toolchain dependency and set `near-sandbox` for tests directly in CI.

### PR DESCRIPTION
**Pull request by mrLSD**
## Description

Removed toolchain dependency and set `near-sandbox` for tests directly in CI.

### CODE REVIEW

**Review by aleksuss — CHANGES_REQUESTED** [review]
Bump the `near-workspaces` as well.

**Comment by mrLSD** [comment]
> Bump the `near-workspaces` as well.

I think it's out of scope for this PR.

**Comment by aleksuss** [comment]
By bumping near-workspaces you don't need to add this: 
```
- name: Install sandbox
         run: |
           if [[ ! -f ${{ env.NEAR_SANDBOX_BIN_PATH }} ]]; then
             rm -rf nearcore
             git clone --depth 1 --branch 1.35.0 https://github.com/near/nearcore
             cd nearcore
             make sandbox-release
             cp target/release/near-sandbox $HOME/bin/
             cache-util save sandbox:${{ env.NEAR_SANDBOX_BIN_PATH }}          
             cd ../
             rm -rf nearcore
           fi
```

**Comment by mrLSD** [comment]
Fully resolved in #37

**Pull request closed without merging**
